"""initial schema

Revision ID: 17ac4c2dde22
Revises: 
Create Date: 2026-08-01 01:30:40.282802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ac4c2dde22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feeder_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feeder_code')
    )
    op.create_index(op.f('ix_feeders_id'), 'feeders', ['id'], unique=False)
    op.create_table('transformers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformer_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity_kva', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('households_served', sa.Integer(), nullable=True),
    sa.Column('feeder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feeder_id'], ['feeders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transformer_code')
    )
    op.create_index(op.f('ix_transformers_id'), 'transformers', ['id'], unique=False)
    op.create_table('poles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pole_code', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('seq_on_line', sa.Integer(), nullable=False),
    sa.Column('pole_type', sa.String(), nullable=True),
    sa.Column('ward', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('transformer_id', sa.Integer(), nullable=False),
    sa.Column('parent_pole_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_pole_id'], ['poles.id'], ),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id'),
    sa.UniqueConstraint('pole_code')
    )
    op.create_index(op.f('ix_poles_id'), 'poles', ['id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pole_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('energized', sa.Boolean(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('battery_mv', sa.Integer(), nullable=False),
    sa.Column('rssi', sa.Integer(), nullable=False),
    sa.Column('fw', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pole_id'], ['poles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pole_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pole_id'], ['poles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_poles_id'), table_name='poles')
    op.drop_table('poles')
    op.drop_index(op.f('ix_transformers_id'), table_name='transformers')
    op.drop_table('transformers')
    op.drop_index(op.f('ix_feeders_id'), table_name='feeders')
    op.drop_table('feeders')
    # ### end Alembic commands ###
