"""create pole_status table

Revision ID: 1e75d3b53843
Revises: 17ac4c2dde22
Create Date: 2026-08-01 17:52:07.443838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e75d3b53843'
down_revision: Union[str, Sequence[str], None] = '17ac4c2dde22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pole_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pole_id', sa.Integer(), nullable=False),
    sa.Column('energized', sa.Boolean(), nullable=False),
    sa.Column('last_event', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pole_id'], ['poles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pole_id')
    )
    op.create_index(op.f('ix_pole_status_id'), 'pole_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pole_status_id'), table_name='pole_status')
    op.drop_table('pole_status')
    # ### end Alembic commands ###
