"""create scheduled outages table

Revision ID: 2abee737ca97
Revises: 1e75d3b53843
Create Date: 2026-08-02 23:14:49.135730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abee737ca97'
down_revision: Union[str, Sequence[str], None] = '1e75d3b53843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_outages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outage_id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outage_id')
    )
    op.create_index(op.f('ix_scheduled_outages_id'), 'scheduled_outages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_outages_id'), table_name='scheduled_outages')
    op.drop_table('scheduled_outages')
    # ### end Alembic commands ###
